// Alan & Frequency

// Smaple Input
// 4
// aman

// Sample Output
// a-2
// m-1
// n-1


function runProgram(input){
    // Write Code Here
    
    input = input.trim().split("\n");
    let N = +input[0];
    let str = input[1];
    
 //   console.log(N,str);
    AlanFrequency(N,str);
 }
 
    function AlanFrequency(N,str){
       let obj = {};
       for(let el of str){
          obj[el] = obj[el] + 1 || 1;   
       }
      // console.log(obj);
       
       let string = "abcdefghijklmnopqrstuvwxyz";
       let bag = "";
       for(let el of string){
         if(obj[el]){
             bag += el + "-" + obj[el] + "\n";
             
         }
         
       }
       console.log(bag);
    }
    
    
    
 if (process.env.USERNAME === "") {
      runProgram(``);
  } else {
      process.stdin.resume();
      process.stdin.setEncoding("ascii");
      let read = "";
      process.stdin.on("data", function (input) {
          read += input;
      });
      process.stdin.on("end", function () {
          read = read.replace(/\n$/, "");
          read = read.replace(/\n$/, "");
          runProgram(read);
      });
      process.on("SIGINT", function () {
          read = read.replace(/\n$/, "");
          runProgram(read);
          process.exit(0);
      });
  }

// Description

// Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, 
// generated by their encryption device “Enigma”. To find the distribution of characte
// 1s, he needs to find out how many times a particular character appears in a string. But, to feed the data 
// into his computer, “Christopher”, he needs the data in lexicographic order, th
// atis, in alphabetical order. Since, he is busy making “Christopher” better, he asks you for help.
//  Help Alan find the frequency of characters in the encrypted strings in alphabetical ord
// er. The string contains only lower case alphabets.

// Input
// The first line contains N, the length of the string, and the next line contains the string itself.
// 1 <= N<=100

// Output
// For each unique character in the string, print the character along with its frequency in the encrypted string, 
// separated by ', on a new line.